sudo:
  false

email:
  false

cache:
  bundler

env:
  global:
    - CODECOV_TOKEN="c711db27-63bc-4710-a10f-452de9e6014b"

before_install:
  - gem update bundler

language:
  ruby

rvm:
  - 2.3.0
  - 2.3.1
  - 2.3.2
  - 2.3.3
  - 2.3.4
  - 2.3.5
  - 2.3.6
  - 2.3.7
  - 2.3.8
  - 2.4.1
  - 2.5.0

script:
  - bundle exec rake coverage
