sudo:
  false

email:
  false

cache:
  bundler

env:
  global:
    - CODECOV_TOKEN="c711db27-63bc-4710-a10f-452de9e6014b"

before_install:
  - gem update bundler

language:
  ruby

rvm:
  - 2.3.1
  - 2.3.2
  - 2.3.3
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6.1

script:
  - bundle exec rake coverage
