sudo:
  false

email:
  false

cache:
  bundler

before_install:
  - gem update bundler

after_success:
  - bundle exec codeclimate-test-reporter

language:
  ruby

rvm:
  - 2.3.0
  - 2.3.1
  - 2.4.1
  - 2.5.0

script:
  - bundle exec rake spec

addons:
  code_climate:
    repo_token: ab20c4024c80ee5ca492cf40f0039212d6aad4c8680c861042970d76a42005df
